### ISSUE TITLE
Create Functional Diagram for Coms

### ISSUE THREAD

**Issue by matthewlewis112** [NGCP/HEX#13]
https://en.wikipedia.org/wiki/Functional_block_diagram

**Comment by matthewlewis112** [comment]
Put finished diagram here: https://github.com/NGCP/HEX/wiki/Functional-Diagrams

**Comment by scallait** [comment]
![ComsFD](https://user-images.githubusercontent.com/71291167/110016324-bd438b80-7cd9-11eb-88ce-5d0d45558fd1.png)

**Comment by scallait** [comment]
![ComsFD (1)](https://user-images.githubusercontent.com/71291167/110016848-5f637380-7cda-11eb-8cbe-85cd1d9b717c.png)
