### ISSUE TITLE
Set Up Travis CI

### ISSUE THREAD

**Issue by matthewlewis112** [NGCP/HEX#14]
Homepage: https://travis-ci.org/
Travis is a continuous integration tool. Tldr; it builds our code, runs our unit tests, and lets us know if our most recent commit broke anything. 
This will involve creating a travis.yml
The GitHub Actions tab might have an automatic tool for this.

**Comment by kibby111701** [comment]
I have a really base level version of the travis file ready to go. It's pretty much identical to the version shown in the Travis docs. If that works I can submit it for a pull request or I can change it so that it looks more like the travis file for the vtol project

**Comment by matthewlewis112** [comment]
Submit it for a pull request and I will cut additional issues to do edits
