### ISSUE TITLE
Create starter requirements.txt

### ISSUE THREAD

**Issue by gwholland3** [NGCP/HEX#3]
## Summary
Add a requirements.txt file containing basic python modules

## Details
* Create a file named requirements.txt in the root directory of the repo
* Add some basic python modules to the text file, with each module on its own line
* For example: dronekit, numpy

**Comment by matthewlewis112** [comment]
https://blog.usejournal.com/why-and-how-to-make-a-requirements-txt-f329c685181e

**Comment by matthewlewis112** [comment]
Can you add pylint to requirements.txt?

**Comment by yanivsagy** [comment]
Uploaded requirements.txt
